### PR TITLE
Changed serial system to use offsets instead of pure addresses. Added…

### PR DESCRIPTION
**Pull request by Kswin01**
… imx driver back to sDDF.

### CODE REVIEW

**Comment by Ivan-Velickovic** [comment]
The i.MX8MM driver should be in a separate commit

**Comment by Ivan-Velickovic** [comment]
I think both the multiplexors and drivers should be checking that the given offset is valid.

Another thing is that we'll have to update the other serial drivers.

**Comment by Ivan-Velickovic** [comment]
> Another thing is that we'll have to update the other serial drivers.

My bad it looks like you already did that.

**Comment by isubasinghe** [comment]
@Kswin01 what was the motivation for using offsets instead of pure addresses? I presume verification?
Asking because it is likely relevant for us as well.

**Comment by Ivan-Velickovic** [comment]
> @Kswin01 what was the motivation for using offsets instead of pure addresses? I presume verification? Asking because it is likely relevant for us as well.

If it's not fixed addresses then all the data memory regions have to be mapped at the same virtual address which is a less than ideal restriction.

**Comment by Ivan-Velickovic** [comment]
This is what the network components do already so we should be consistent with them as well.

**Comment by Ivan-Velickovic** [comment]
The general issue of using offsets throughout an sDDF sub-system or doing translation in the multiplexors is actively being discussed - will review once we've decided what to do.

**Comment by Ivan-Velickovic** [comment]
Closed since there is either a merged PR for some of the commits or an open PR.

**Pull request closed without merging**
