### PR TITLE
Fix buffer length read from descriptor in dwmac

### PR DESCRIPTION
**Pull request by dhaliman**
Length is read incorrectly from `rdes3` descriptor in dwmac driver which causes FCS errors. 0-14 bits of the descriptor are for length and an appropriate mask has been applied.

### CODE REVIEW

**Comment by Ivan-Velickovic** [comment]
You'll need to rebase on main and resolve the conflicts, there should only be one commit to fix bug, the easiest way to do it is create a new branch and cherry-pick just the fix so you don't have the other commits in there that add echo server support for Star64 etc.

**Comment by Kswin01** [comment]
The fix looks good to me as we discussed, but as Ivan mentioned if you could rebase/cherry-pick that would be great!

**Comment by dhaliman** [comment]
> You'll need to rebase on main and resolve the conflicts, there should only be one commit to fix bug, the easiest way to do it is create a new branch and cherry-pick just the fix so you don't have the other commits in there that add echo server support for Star64 etc.

Apologies for not rebasing. 

The fix is for star64 driver which isn't on main yet. Wouldn't I want to rebase on star64_eth? And then get this merged on star64_eth?

**Comment by Kswin01** [comment]
Closing this as https://github.com/au-ts/sddf/pull/271 is the updated version.

**Pull request closed without merging**
